auth:
  "example-auth-token": "username"
  "example-auth-hash2" : "username2"

# OSRM PATH
# String contains ${root}, ${data}, ${scripts}, ${public}
# WILL BE REPLACE
osrm:
  path: ${data}/osrm/indonesia-latest.osrm
geoip:
  country: ${data}/geoip/GeoIP-Country.mmdb
  city: ${data}/geoip/GeoIP-City.mmdb
