auth:
  "example-auth-token": "username"
  "example-auth-hash2" : "username2"

# Result without JSON prettify
minify: false

# ALLOWED CORS REFERER
referer:
  example.com

# OSRM PATH
# String contains ${root}, ${data}, ${scripts}, ${public}
# WILL BE REPLACE
osrm:
  # OSRM File to read ( we only currently support indonesia)
  path: ${data}/osrm/indonesia-latest.osrm
  algorithm: "MLD"
  mmap_memory: true
  # I try to test with shared memory and it was hung up on calll new OSRM()
  shared_memory: false
geoip:
  # GEO IP FILE
  country: ${data}/geoip/GeoIP-Country.mmdb
  city: ${data}/geoip/GeoIP-City.mmdb
